### ISSUE TITLE
Highlight type definition language

### ISSUE THREAD

**Issue by stubailo** [rmosolgo/language-graphql#3]
I think READMEs will often want to describe their schema in GraphQL form, like so:

``` graphql
type Comment {
  postedBy: User!
  createdAt: String! # Actually a date
  content: String!
}

type Entry {
  repository: Repository!
  postedBy: User!
  createdAt: String! # Actually a date
  score: Int!
  comments: [Comment]! # Should this be paginated?
  commentCount: Int!
}
```

As you can see, comments and arguments are highlighted but not other stuff. It would be cool to highlight for example the `type` keyword, the types, etc.

**Comment by rmosolgo** [comment]
This is hard! 

Consider these two cases: 


```graphql 
query {
  field1: field
  field2: field 
}
```

```graphql 
schema {
  query: QueryType
  mutation: MutationType
}
```

In the first case, it's a query, followed by selections, and each selection has an alias. In the second case, it's a schema definition, followed by field definitions. 

As far as I can tell, atom grammars (like textmate grammars before them) don't have any mechanism for "followed by this named pattern". You can define a bunch of _small_ patterns, then hope they come together, but I can't say, like `/schema\s+\\{<%= fieldDefinitions %>\\}/`, because you can't insert a named entity like that. 

Selections _have_ to be part of the root level grammar to support unnamed queries, eg 

```
{ field1, field2 }
```

But then they conflict with field definitions! 

I'll poke and prod some more, but as far as I can tell, the only way to disambiguate would be to hardcode the _entire_ regular expression, using copy-and-paste for reused elements like directives. Yuck! 

I'll probably try again another day, and if it doesnt work, I'll investigate options for _generating_ the `.cson` file

**Comment by rmosolgo** [comment]
Arg!!!!

![image](https://cloud.githubusercontent.com/assets/2231765/17947541/1ac2bb18-6a1b-11e6-8660-4d21886352a1.png)

**Comment by asiandrummer** [comment]
@rmosolgo Could we maybe separate the current rule into `#operationDefinitions` repository and have a separate repository for `#schemaDefinition`? Something like this:
```
{
  'name': 'meta.operation'
  'comment': 'an operation definition'
  'match': '(query|mutation|subscription)\\s*([_A-Za-z][_0-9A-Za-z]*)'
  'captures':
  '1':
    'name': 'storage.type'
  '2':
    'name': 'variable.other'
  'patterns': [
    'include' : '#operations'
  ]
},
{
  'name': 'meta.operation'
  'comment': 'a schema definition'
  'match': '(schema)\\s*([_A-Za-z][_0-9A-Za-z]*)'
  'captures':
  '1':
    'name': 'storage.type'
  '2':
    'name': 'variable.other'
  'patterns': [
    'include' : '#schemaDefinitions'
  ]
}
```

**Comment by rmosolgo** [comment]
I considered something like that, but gave up before trying :S 

My understanding of `include` (taken solely from https://manual.macromates.com/en/language_grammars) is that it can be used two places: 

- the "global" patterns list  
- a nested patterns list, when the parent has `begin` and `end` 

I tried to imagine what would be required for a `begin` and `end` and that's where I gave up. The _logical_ `begin` & `end` is `{ ... }`, but of course, that's not specific enough, that's the whole problem! To _actually_ code the begin & end, I'm afraid you'd have to hardcode the whole "header" (eg, `extend type X implements Y, Z`, `input B @whateverDirective(arg: "str")`)  with opening `{` as "begin", then "end" would be just `}`.  

Since there's no (not that i could find) recipe for reusing a pattern inside another pattern, you'd have to hardcode literals _again_ (for directive arguments). 

Another issue I had, although I only tried for a couple minutes, was capturing elements from a repeating pattern (specifically `{typename}, {typename}, {typename}`). The goal is to highlight the typenames but not the commas. I couldn't figure out how to access

**Comment by rmosolgo** [comment]
I became aware via a [duplicate package](https://atom.io/packages/language-graphql-lb) that `language-babel` has [GraphQL higihlighting](https://github.com/gandm/language-babel/blob/master/grammars/Babel%20Language.json#L2658). Judging by the previews, it has fewer and different bugs, so as soon as I can, I will review that one and see if I can learn any tricks from it!

**Comment by rmosolgo** [comment]
0.8.0 includes a copy-paste of graphql highlighting from language-babel. 

It has much better support for schema language. Please reopen another issue if you find a specific bug!
